# Generated by Django 5.0.6 on 2024-06-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='personal_note',
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
