# Generated by Django 5.0.6 on 2024-06-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_sold',
        ),
    ]
