# Generated by Django 5.0.6 on 2024-07-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_a_offer',
            field=models.BooleanField(default=False),
        ),
    ]
