# Generated by Django 5.0.6 on 2024-06-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
